name: macro_store
description: A simple macro to make private fields reactive
version: 0.1.0
repository: https://github.com/boginni/macro_store

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  macros: ^0.1.0