name: macro_store
description: A simple macro to make private fields reactive
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.4.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  macros: ^0.1.0