name: macro_store
description: A simple macro to make private fields reactive
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  macros: ^0.1.0-main.5